# Getting started

## Tensors

Importing torch:

In [1]:
import torch

Constructing a 5x3 matrix, unitialized

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 4.3935e+21],
        [4.5737e-41, 4.3935e+21, 4.5737e-41],
        [4.3935e+21, 4.5737e-41, 2.3308e-09],
        [6.4097e-10, 2.3308e-09, 4.2966e-05],
        [2.3308e-09, 6.4097e-10, 2.3308e-09]])


Constructing a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5940, 0.0936, 0.8110],
        [0.3550, 0.9328, 0.4200],
        [0.2277, 0.5967, 0.8434],
        [0.8568, 0.7763, 0.9107],
        [0.0988, 0.1829, 0.3187]])


Constructing a matrix filled with zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Constructing a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor (e.g., dtype) unless new values are provided by user:


In [7]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype, result has the same size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8273,  1.8244,  0.2978],
        [-0.9299, -0.4245,  0.3211],
        [-0.9264, -0.8662, -0.0582],
        [ 1.2716, -0.2742,  1.1162],
        [ 0.3834, -0.0589, -0.4460]])


Get its size:

In [8]:
print(x.size())

torch.Size([5, 3])


NOTE: torch.Size is in fact a tuple, so it supports all tuple operations

## Operations

There are multiple syntaxes for opertations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3407,  2.2974,  0.7830],
        [-0.0508,  0.3363,  1.1058],
        [-0.1368, -0.6068,  0.5570],
        [ 1.6190,  0.4274,  1.4410],
        [ 0.8555,  0.0132,  0.1893]])


Addition: syntax 2

In [10]:
print(torch.add(x, y))

tensor([[ 1.3407,  2.2974,  0.7830],
        [-0.0508,  0.3363,  1.1058],
        [-0.1368, -0.6068,  0.5570],
        [ 1.6190,  0.4274,  1.4410],
        [ 0.8555,  0.0132,  0.1893]])


Addition: providing an output tensor as argument

In [12]:
results = torch.empty(5, 3)
torch.add(x, y, out=results)
print(results)

tensor([[ 1.3407,  2.2974,  0.7830],
        [-0.0508,  0.3363,  1.1058],
        [-0.1368, -0.6068,  0.5570],
        [ 1.6190,  0.4274,  1.4410],
        [ 0.8555,  0.0132,  0.1893]])


Addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3407,  2.2974,  0.7830],
        [-0.0508,  0.3363,  1.1058],
        [-0.1368, -0.6068,  0.5570],
        [ 1.6190,  0.4274,  1.4410],
        [ 0.8555,  0.0132,  0.1893]])


NOTE: Any operation that mutates a tensor in-place is post-fixed with an `_`.

You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([ 1.8244, -0.4245, -0.8662, -0.2742, -0.0589])


Resizing: if you want to resize/reshape tensor, you can use `torch.view`:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8139])
0.813943088054657


READ LATER: 100+ Tensor operations are described [here](https://pytorch.org/docs/torch)

## NumPy Bridge

### Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value:

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how chaning the np array changed the Torch Tensor automatically:

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU expect CharTensor support converting to NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    x = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("CUDA device not available!")

CUDA device not available!
