# Getting started

## Tensors

Importing torch:

In [1]:
import torch

Constructing a 5x3 matrix, unitialized

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-8.3630e-09,  4.5562e-41, -8.3630e-09],
        [ 4.5562e-41,  6.3010e-36,  6.3010e-36],
        [ 6.3010e-36,  6.3010e-36,  6.3010e-36],
        [ 6.3010e-36,  6.3010e-36,  6.3010e-36],
        [ 2.5204e-35,  6.3010e-36,  6.3010e-36]])


Constructing a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3386, 0.4227, 0.6162],
        [0.4365, 0.6354, 0.6466],
        [0.9439, 0.6022, 0.6325],
        [0.2573, 0.9409, 0.3506],
        [0.5770, 0.9913, 0.3016]])


Constructing a matrix filled with zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Constructing a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor (e.g., dtype) unless new values are provided by user:


In [6]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype, result has the same size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0320, -0.5320, -0.2668],
        [-0.0931,  1.0280, -0.1892],
        [ 0.8350, -0.8720,  1.4939],
        [-0.2459,  1.6777, -0.0327],
        [ 0.7598,  1.4575,  0.3943]])


Get its size:

In [7]:
print(x.size())

torch.Size([5, 3])


NOTE: torch.Size is in fact a tuple, so it supports all tuple operations

## Operations

There are multiple syntaxes for opertations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2985,  0.0981, -0.2521],
        [ 0.8783,  1.7557,  0.7941],
        [ 0.8634, -0.5114,  2.1266],
        [ 0.1533,  2.4142,  0.3855],
        [ 1.1874,  2.4200,  1.0431]])


Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[ 1.2985,  0.0981, -0.2521],
        [ 0.8783,  1.7557,  0.7941],
        [ 0.8634, -0.5114,  2.1266],
        [ 0.1533,  2.4142,  0.3855],
        [ 1.1874,  2.4200,  1.0431]])


Addition: providing an output tensor as argument

In [10]:
results = torch.empty(5, 3)
torch.add(x, y, out=results)
print(results)

tensor([[ 1.2985,  0.0981, -0.2521],
        [ 0.8783,  1.7557,  0.7941],
        [ 0.8634, -0.5114,  2.1266],
        [ 0.1533,  2.4142,  0.3855],
        [ 1.1874,  2.4200,  1.0431]])


Addition: in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.2985,  0.0981, -0.2521],
        [ 0.8783,  1.7557,  0.7941],
        [ 0.8634, -0.5114,  2.1266],
        [ 0.1533,  2.4142,  0.3855],
        [ 1.1874,  2.4200,  1.0431]])


NOTE: Any operation that mutates a tensor in-place is post-fixed with an `_`.

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([-0.5320,  1.0280, -0.8720,  1.6777,  1.4575])


Resizing: if you want to resize/reshape tensor, you can use `torch.view`:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5186])
-0.5185829997062683


READ LATER: 100+ Tensor operations are described [here](https://pytorch.org/docs/torch)

## NumPy Bridge

### Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value:

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how chaning the np array changed the Torch Tensor automatically:

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU expect CharTensor support converting to NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    x = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("CUDA device not available!")

tensor([[-0.8486,  0.2308, -0.4432,  0.7459,  1.3090, -0.0723, -0.9104,  0.3592],
        [ 0.1447,  0.6336, -0.4344, -0.2593, -1.5283, -0.0281, -0.1385,  1.1531]])
tensor([[-0.8486,  0.2308, -0.4432,  0.7459,  1.3090, -0.0723, -0.9104,  0.3592],
        [ 0.1447,  0.6336, -0.4344, -0.2593, -1.5283, -0.0281, -0.1385,  1.1531]],
       dtype=torch.float64)
